### ISSUE TITLE
Crasher after a while

### ISSUE THREAD

**Issue by tsathoqqua** [fluffos/lima#2]
```Stack trace (most recent call last):
#9    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#8    Object "./driver", at 0x5576699e7749, in _start
#7    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f505db75e0a, in __libc_start_main
#6    Object "./driver", at 0x5576699e7252, in
#5    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7f505d29924e, in event_base_loop
#4    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7f505d2989ad, in
#3    Object "./driver", at 0x557669ae36bc, in
#2    Object "/lib/x86_64-linux-gnu/libjemalloc.so.2", at 0x7f505d36ca2d, in operator delete(void*, unsigned long)
#1    Object "/lib/x86_64-linux-gnu/libjemalloc.so.2", at 0x7f505d2f1155, in
#0    Object "/lib/x86_64-linux-gnu/libjemalloc.so.2", at 0x7f505d367629, in
Segmentation fault (Address not mapped to object [0x153198])
Segmentation fault
```
Seems to crash every few minutes. Nothing is happening.

**Comment by thefallentree** [comment]
Please add  -DENABLE_SANITIZER=ON in build.sh at the cmake line,  rebuild and re-run, that will give you better error messages

**Comment by tsathoqqua** [comment]
Really like the build setup! Very modern! :)
DONE, but after I built it with this switch it doesn't crash. Been running for 30 minutes now.

**Comment by thefallentree** [comment]
Yeah, but if it prints out warnings,  you can post that too 

There are a bunch of warnings in the function.cc that I will be fixing.

**Comment by tsathoqqua** [comment]
```
[2020/04/08 00:24:25:6645] N:  forbidding on uri sanitation
[2020/04/08 08:21:55:2151] N:  forbidding on uri sanitation
^CStack trace (most recent call last):
#8    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#7    Object "./build/bin/driver", at 0x556e9a22eba9, in _start
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f4e4d4dfe0a, in __libc_start_main
#5    Object "./build/bin/driver", at 0x556e9a227cf6, in
#4    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7f4e4ceddff4, in event_base_loop
#3    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7f4e4cee7d28, in
#2    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f4e4d5b6596, in epoll_wait
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f4e4d4f47df, in
#0    Object "./build/bin/driver", at 0x556e9aa33d78, in
******** FATAL ERROR: SIGINT: Process interrupted
FluffOS driver attempting to exit gracefully.
*Error: unable to open stat file domain_stats for writing.
*Error: unable to open stat file author_stats for writing.
Eval interrupted: object secure/master cost limit reached, limit: 2000000 usec.
=================================================================
==29225==ERROR: AddressSanitizer: global-buffer-overflow on address 0x556e9b7b6c90 at pc 0x556e9a82df5e bp 0x7ffd534cd430 sp 0x7ffd534cd428
READ of size 2 at 0x556e9b7b6c90 thread T0
    #0 0x556e9a82df5d in int_free_svalue(svalue_t*) /home/staun/thefallentree/lima/driver/src/vm/internal/base/svalue.cc:74
    #1 0x556e9a209fd3 in pop_stack() /home/staun/thefallentree/lima/driver/src/vm/internal/base/interpret.cc:515
    #2 0x556e9a209fd3 in pop_n_elems(int) /home/staun/thefallentree/lima/driver/src/vm/internal/base/interpret.cc:1097
    #3 0x556e9a209fd3 in restore_context(error_context_t*) /home/staun/thefallentree/lima/driver/src/vm/internal/base/interpret.cc:4792
    #4 0x556e9a2056c0 in safe_apply(char const*, object_t*, int, int) /home/staun/thefallentree/lima/driver/src/vm/internal/apply.cc:349
    #5 0x556e9a2056c0 in safe_apply_master_ob(int, int) /home/staun/thefallentree/lima/driver/src/vm/internal/master.cc:53
    #6 0x556e9a76f8fe in fatal(char const*, ...) /home/staun/thefallentree/lima/driver/src/vm/internal/simulate.cc:1673
    #7 0x556e9aa34118 in attempt_shutdown /home/staun/thefallentree/lima/driver/src/mainlib.cc:189
    #8 0x7f4e4d4f47df  (/lib/x86_64-linux-gnu/libc.so.6+0x3b7df)
    #9 0x7f4e4d5b6595 in epoll_wait ../sysdeps/unix/sysv/linux/epoll_wait.c:30
    #10 0x7f4e4cee7d28  (/lib/x86_64-linux-gnu/libevent-2.1.so.7+0x2dd28)
    #11 0x7f4e4ceddff4 in event_base_loop (/lib/x86_64-linux-gnu/libevent-2.1.so.7+0x23ff4)
    #12 0x556e9a227cf6 in backend(event_base*) /home/staun/thefallentree/lima/driver/src/backend.cc:232
    #13 0x556e9a227cf6 in driver_main /home/staun/thefallentree/lima/driver/src/mainlib.cc:368
    #14 0x556e9a227cf6 in main /home/staun/thefallentree/lima/driver/src/main.cc:5
    #15 0x7f4e4d4dfe0a in __libc_start_main ../csu/libc-start.c:308
    #16 0x556e9a22eba9 in _start (/home/staun/thefallentree/lima/build/bin/driver+0xb3eba9)

0x556e9b7b6c90 is located 16 bytes to the left of global variable '_stack' defined in '/home/staun/thefallentree/lima/driver/src/vm/internal/base/interpret.cc:83:17' (0x556e9b7b6ca0) of size 1048896
0x556e9b7b6c90 is located 40 bytes to the right of global variable 'fp' defined in '/home/staun/thefallentree/lima/driver/src/vm/internal/base/interpret.cc:74:11' (0x556e9b7b6c60) of size 8
SUMMARY: AddressSanitizer: global-buffer-overflow /home/staun/thefallentree/lima/driver/src/vm/internal/base/svalue.cc:74 in int_free_svalue(svalue_t*)
Shadow bytes around the buggy address:
  0x0aae536eed40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eed50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eed60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eed70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eed80: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 f9 f9 f9
=>0x0aae536eed90: f9 f9[f9]f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eeda0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eedb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eedc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eedd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae536eede0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==29225==ABORTING
```
(It ran all night without issues. I got the above at Ctrl-C)

**Comment by thefallentree** [comment]
Yeah, during ctrl+C all bets are off anyway, so I wouldn't worry about this.
